
spring:
  application:
    name: webapp
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: hims
    password: root
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          format_sql: true
    show-sql: true


server:
  port: 4040
