
spring:
  application:
    name: webapp
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: hims
    password: root

    hikari:
      maximum-pool-size: 10
      pool-name: HikariCP
      minimum-idle: 2
      idle-timeout: 30000          # 30 seconds
      max-lifetime: 1800000        # 30 minutes
      connection-timeout: 30000    # 30 seconds
      auto-commit: true

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update # update/ none/ created
    properties:
        hibernate:
          format_sql: true
    show-sql: true

server:
  port: 5050

spring.mvc.pathmatch.matching-strategy: ant_path_matcher
# Collapse all endpoints by default
springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha # Sort controllers alphabetically
    operations-sorter: alpha # Sort operations inside controllers alphabetically
  api-docs:
   enabled: true
   swagger-ui:
    enabled: true
   show-actuator: true
   use-fqn: true
   model-converters:
    jackson:
      enabled: true